# Generated by Django 2.0.6 on 2019-06-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_book_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='charges',
            field=models.FloatField(default=0),
        ),
    ]
